
package lt.appcamp.lab.mylab4;

import java.util.ArrayList;

import android.content.ContentValues;

public class ContentPopulator {

    private MyDatabase database;
    private ArrayList<ContentValues> peopleValues = new ArrayList<ContentValues>();

    ContentPopulator(MyDatabase database) {
        this.database = database;
    }

    public void populatePeoples() {

        put(1,"Käthe Gold","stage actress");
        put(1,"Liane Haid","first Austrian movie star.");
        put(1,"Hans Moser","comedy actor");
        put(1,"Arnold Schwarzenegger","bodybuilder");
        put(1,"Hedy Lamarr","actress; also co-inventor of spread spectrum radio technology; became U.S. citizen");
        put(1,"Christiane Hörbiger","actress a star");
        put(1,"Senta Berger","actress");
        put(1,"Birgit Minichmayr","actress");
        put(1,"Romy Schneider","actress");
        put(1,"Erich von Stroheim","actor and film director");
        put(1,"Leon Askin","actor");
        put(1,"Helmut Berger","actor");
        put(1,"Klaus Maria Brandauer","actor");
        put(1,"Attila Hörbiger","actor");
        put(1,"Paul Hörbiger","actor");
        put(1,"Maximilian Schell","actor");
        put(1,"Christoph Waltz","actor");
        put(1,"Heinz Weixelbraun","actor");
        put(1,"Oskar Werner","actor");
        put(2,"Zhang Heng-Astronomer","mathematician poet official and inventor.");
        put(2,"Zu Chongzhi-Noted","for calculating Pi to seven places");
        put(3,"Marija Omaljev","Grbić");
        put(3,"Ivan Pavletić","actor writer director");
        put(4,"Tõnu Tõniste (born 1967)","yachtsman");
        put(4,"Toomas Tõniste (born 1967)","yachtsman");
        put(4,"Aleksander Aberg (1881–1920)","wrestler");
        put(4,"Georg Hackenschmidt (1878–1968)","wrestler");
        put(4,"Osvald Käpp (1905–1995)","wrestler");
        put(4,"Martin Klein (1884–1947)","wrestler");
        put(4,"Anton Koolmann (1899–1953)","wrestler");
        put(4,"Johannes Kotkas (1915–1998)","wrestler");
        put(4,"Albert Kusnets (1902–1942)","wrestler");
        put(4,"Georg Lurich (1876–1920)","wrestler");
        put(4,"August Neo (1908–1982)","wrestler");
        put(4,"Kristjan Palusalu (1908–1987)","wrestler");
        put(4,"Eduard Pütsep (1898–1960)","wrestler");
        put(4,"Roman Steinberg (1900–1928)","wrestler");
        put(4,"Voldemar Väli (1903–1997)","wrestler");
        put(4,"Tarmo Mitt (born 1977)","World Strong Man");
        put(4,"Jaan Kikkas (1892–1944)","weightlifter");
        put(4,"Arnold Luhaäär (1905–1965)","weightlifter");
        put(4,"Alfred Neuland (1895–1966)","weightlifter");
        put(4,"Alfred Schmidt (1898–1972)","weightlifter");
        put(4,"Jaan Talts (born 1944)","weightlifter");
        put(4,"Maret Ani (born 1982)","tennis player");
        put(4,"Kaia Kanepi (born 1985)","tennis player");
        put(4,"Anett Kontaveit (born 1995)","tennis player");
        put(4,"Sven Salumaa (born 1966)","tennis player");
        put(4,"Ants Antson (born 1938)","speedskater");
        put(4,"Jaak Mae (born 1972)","skier");
        put(4,"Kristina Šmigun-Vähi (born 1977)","skier");
        put(4,"Andrus Veerpalu (born 1971)","skier");
        put(4,"Jüri Jaanson (born 1965)","rower");
        put(4,"Markko Märtin (born 1975)","rally driver");
        put(4,"Marko Asmer (born 1984)","racing driver");
        put(4,"Toomas Edur (born 1954","NHL hockey player");
        put(4,"Tanel Leok (born 1985)","motocross rider");
        put(4,"Jane Salumäe (born 1968)","marathon runner");
        put(4,"Jüri Lossmann (1891–1984)","long distance runner");
        put(4,"Aleksei Budõlin (born 1976)","judoka");
        put(4,"Indrek Pertelson (born 1971)","judoka");
        put(4,"Harald Tammer (1899–1942)","journalist");
        put(4,"Moonika Aava (born 1979)","javelin thrower");
        put(4,"Andrus Värnik (born 1977)","javelin thrower");
        put(4,"Siim Liivik (born 1988)","ice hockey player");
        put(4,"Toivo Suursoo (born 1975)","ice hockey player");
        put(4,"Jüri Tarmak (born 1946)","high jumper");
        put(4,"Joel Lindpere (born 1981)","footballer for New York Red Bulls and the Estonian National Team");
        put(4,"Eduard Ellman-Eelma (1902–1943)","football player");
        put(4,"Marko Kristal (born 1973)","football player");
        put(4,"Andres Oper (born 1977)","football player");
        put(4,"Mart Poom (born 1972)","football player");
        put(4,"Gerd Kanter (born 1979)","discus thrower");
        put(4,"Aleksander Tammert (born 1973)","discus thrower");
        put(4,"Aleksander Klumberg (1899–1958)","decathlete");
        put(4,"Heino Lipp (1922–2006)","decathlete");
        put(4,"Erki Nool (born 1970)","decathlete");
        put(4,"Kristjan Rahnu (born 1979)","decathlete");
        put(4,"Lauri Aus (1970–2003)","cyclist");
        put(4,"Jaan Kirsipuu (born 1969)","cyclist");
        put(4,"Erika Salumäe (born 1962)","cyclist");
        put(4,"Ortvin Sarapu (1924–1999)","chess player (New Zealand)");
        put(4,"Friedrich Amelung (1842–1909)","chess player");
        put(4,"Jaan Ehlvest (born 1962)","chess player");
        put(4,"Gunnar Friedemann (1909–1943)","chess player");
        put(4,"Paul Keres (1916–1975)","chess player");
        put(4,"Lionel Kieseritzky (1806–1853)","chess player");
        put(4,"Leho Laurine (1904–1998)","chess player");
        put(4,"Iivo Nei (born 1931)","chess player");
        put(4,"Tõnu Õim (born 1941)","chess player");
        put(4,"Lembit Oll (1966–1999)","chess player");
        put(4,"Ilmar Raud (1913–1941)","chess player");
        put(4,"Salme Rootare (1913–1987)","chess player");
        put(4,"Vidrik Rootare (c. 1900–1985)","chess player");
        put(4,"Paul Felix Schmidt (1916–1984)","chess player");
        put(4,"Johannes Türn (1898–1993)","chess player");
        put(4,"Meelis Kanep (born 1983)","chess grandmaster");
        put(4,"Nikolai Stepulov (1913–1968)","boxer");
        put(4,"Michael Roos (Mihkel Roos","born 1982)");
        put(4,"Tiit Sokk (born 1964)","basketball player (1988 Olympic Gold Medalist for USSR)");
        put(4,"Martin Müürsepp (born 1974)","basketball player");
        put(4,"Michael Roos (born 1982)","American football player");
        put(5,"Kain Tapper","sculptor (1930–2004)");
        put(5,"Reidar Särestöniemi","painter (1925–1981)");
        put(5,"Eija-Liisa Ahtila – photographer","video artist (born 1959)");
        put(5,"Tove Jansson painter","illustrator");
        put(6,"Fabrice Benichou","world champion super bantamweight boxer");
        put(6,"Georges Carpentier","world champion boxer");
        put(6,"Marcel Cerdan","world champion boxer");
        put(6,"Eugène Criqui","world champion boxer");
        put(6,"Marcel Thil","world champion boxer");
        put(6,"Christophe Tiozzo","world champion boxer");
        put(6,"Fabrice Tiozzo","world champion boxer");
        put(6,"Robert Cohen","world champion bantamweight boxer");
        put(6,"Serge Blanco","Venezuela born French citizen");
        put(6,"Marion Bartoli","tennis player");
        put(6,"Stéphanie Cohen-Aloro","tennis player");
        put(6,"Pierre Darmon","tennis player");
        put(6,"Suzanne Lenglen","tennis player");
        put(6,"Amélie Mauresmo","tennis player");
        put(6,"Yannick Noah","tennis player");
        put(6,"Marlène Harnois (born 1986)","taekwondo practitioner");
        put(6,"Laure Manaudou","swimmer");
        put(6,"Jeremy Flores","surfer");
        put(6,"Myriam Fox-Jerusalmi","slalom canoer");
        put(6,"Jean-Claude Killy","skier");
        put(6,"Carole Montillet","skier");
        put(6,"Patrick Vieira","Senegal born French citizen");
        put(6,"Jacques Fouroux","rugby union player and coach");
        put(6,"Sébastien Loeb","rally driver and 5-time champion");
        put(6,"Émile Delahaye","race car pioneer");
        put(6,"Camille du Gast","race car driver");
        put(6,"Jean-Pierre Wimille","race car driver");
        put(6,"André the Giant","professional wrestler");
        put(6,"Hellé Nice","pioneer female race car driver");
        put(6,"Sarah Abitbol","pairs figure skater (with S. Bernadis); World Figure Skating Championship bronze[1]");
        put(6,"Stéphane Bernadis","pairs figure skater (with S. Abitbol)");
        put(6,"Alain Bernard","Olympic swimmer");
        put(6,"Jean Bloch","Olympic silver football player");
        put(6,"Micheline Ostermeyer","Olympic champion in discus and shot put");
        put(6,"Joakim Noah","NBA basketball player (Chicago Bulls)");
        put(6,"Olivier Jacque","motorcycle rider");
        put(6,"Richard Virenque","Morocco born French citizen");
        put(6,"Andre Ethier","Major League Baseball outfielder for the Los Angeles Dodgers");
        put(6,"David Douillet","judo");
        put(6,"Jean Cruguet","jockey of Seattle Slew");
        put(6,"Georges Stern","jockey");
        put(6,"François Rozenthal","ice hockey player");
        put(6,"Maurice Rozenthal","ice hockey player");
        put(6,"Pascal Lavanchy","ice dancer (with S. Moniotte)");
        put(6,"Sophie Moniotte","ice dancer (with P. Lavanchy)");
        put(6,"Gwendal Peizerat","ice dancer");
        put(6,"André Fabre","horse trainer");
        put(6,"Cristobal Huet","hockey player");
        put(6,"Marcel Desailly","Ghana born French citizen");
        put(6,"Alain Prost","Formula One driver and 4-time champion");
        put(6,"Max Jean","Formula One driver");
        put(6,"Claude Makélélé","football player: PSG");
        put(6,"Patrice Evra","football player: Monaco + Manchester United");
        put(6,"Fabien Barthez","football player");
        put(6,"Eric Cantona","football player");
        put(6,"Abou Diaby","football player");
        put(6,"Just Fontaine","football player");
        put(6,"Yoann Gourcuff","football player");
        put(6,"Rudy Haddad","football player");
        put(6,"Thierry Henry","football player");
        put(6,"Raymond Kopa","football player");
        put(6,"Bixente Lizarazu","football player");
        put(6,"Michel Platini","football player");
        put(6,"David Trezeguet","football player");
        put(6,"Zinedine Zidane","football (soccer) Player");
        put(6,"Claude Netter","foil fencer");
        put(6,"Surya Bonaly","figure skater");
        put(6,"Alain Calmat","figure skater");
        put(6,"Philippe Candeloro","figure skater");
        put(6,"Brian Joubert","figure skater");
        put(6,"Éric Millot","figure skater");
        put(6,"Lucien Gaudin","fencer");
        put(6,"Julien Pillet","fencer");
        put(6,"Jacques Anquetil","cyclist");
        put(6,"Louison Bobet","cyclist");
        put(6,"Eugène Christophe","cyclist");
        put(6,"Laurent Fignon","cyclist");
        put(6,"Bernard Hinault","cyclist");
        put(6,"Constant Huret","cyclist");
        put(6,"Laurent Jalabert","cyclist");
        put(6,"Jeannie Longo","cyclist");
        put(6,"André Mahé","cyclist");
        put(6,"Jose Meiffret","cyclist");
        put(6,"Roger Walkowiak","cyclist");
        put(6,"Stéphane Peterhansel","car and motor racer");
        put(6,"Mary Pierce","Canadian-born French citizen");
        put(6,"Serge Betsen","Cameroon born French citizen");
        put(6,"Stéphane Haccoun","boxer");
        put(6,"Rene Jacquot","boxer");
        put(6,"Tony Parker","Belgian born French citizen");
        put(6,"Pierre Galle","basketball player and coach");
        put(6,"Tariq Abdul-Wahad","basketball player (born Olivier Saint-Jean)");
        put(6,"Richard Dacoury","basketball player");
        put(6,"Boris Diaw","basketball player");
        put(6,"Antoine Rigaudeau","basketball player");
        put(6,"Alain Mimoun","athlete");
        put(6,"Marie-José Pérec","athlete");
        put(6,"Luc Alphand","Alpine skier");
        put(6,"Andrée Brunet & Pierre Brunet","1928 & 1932 Olympic skating Gold Medalists");
        put(7,"Kálmán Kandó","pioneer in the development of railway electric traction");
        put(7,"Ottó Bláthy","inventor of the voltage regulator");
        put(7,"Tivadar Puskás","inventor of the telephone exchange");
        put(7,"Dénes Gábor","inventor of the holography (1947)");
        put(7,"Csaba Horváth","inventor of the high-performance liquid chromatograph");
        put(7,"Donát Bánki","inventor of the cross-flow turbine");
        put(7,"János Csonka","inventor of the carburetor");
        put(7,"Ferenc Anisits","inventor of the BMW diesel engine (1983)");
        put(7,"Joseph Petzval","inventor of the binocular (1840)");
        put(7,"László Bíró","inventor of the ballpoint pen (1931)");
        put(7,"János Irinyi","inventor of noiseless match (1836)");
        put(7,"Oszkár Asbóth","inventor of helicopter (1928)");
        put(7,"Kálmán Tihanyi","inventor of cathode ray tubes");
        put(7,"Joseph Pulitzer","creator of the Pulitzer Prize (1917)");
        put(7,"József Galamb","creator of the Ford Model T (1908)");
        put(7,"József Dobos","creator of the Dobos cake (1884)");
        put(7,"John von Neumann","computer pioneer (1944)");
        put(7,"Ányos Jedlik","co-inventor of dynamo (1861) and soda water (1826)");
        put(7,"Károly Zipernowsky","co-inventor (with Ottó Bláthy and Miksa Déri) of the transformer");
        put(7,"Miksa Déri","co-inventor (with Ottó Bláthy and Károly Zipernowsky) of the transformer");
        put(8,"Eduardo De Filippo (1900–1984)","playwright and actor. In his scores of plays he combined pathos and farce");
        put(8,"Vittorio Gassman (1922–2000)","film and theatre actor and director");
        put(8,"Ugo Tognazzi (1922–1990)","film and theatre actor");
        put(8,"Totò (1898–1967)","actor. Likened by international film critics to the American film comic Buster Keaton[1]");
        put(8,"Gian Maria Volontè (1933–1994)","actor. He is perhaps best known outside of Italy for his roles in A Fistful of Dollars (1964) and For a Few Dollars More (1965)");
        put(8,"Amedeo Nazzari (1907–1979)","actor. He had a long and distinguished movie career");
        put(8,"Alberto Sordi (1920–2003)","actor. Depicted the vices");
        put(8,"Elio Germano (born 1980)","actor who won the Best Actor Award at the Cannes Film Festival in 2010");
        put(8,"Marcello Mastroianni (1924–1996)","actor who became the preeminent leading man in Italian cinema during the 1960s. He acted in more than 100 movies");
        put(8,"Gino Cervi (1901–1974)","actor and manager best known outside of Italy for his film portrayal of a small-town Communist mayor in the Don Camillo films");
        put(8,"Giancarlo Giannini (born 1942)","actor and dubber");
        put(8,"Massimo Troisi (1953–1994)","actor and director. Internationally");
        put(8,"Terence Hill (born 1939)","actor");
        put(8,"Nino Manfredi (1921–2004)","actor");
        put(8,"Rudolph Valentino (1895–1926)","actor");
        put(8,"Carlo Verdone (born 1950)","actor");
        put(9,"Kārlis Goppers (1876–1941) – general","founder of Latvian Boy Scouts");
        put(10,"Antanas Škėma (1911–1961)","writer in exile");
        put(10,"Vincas Kudirka (1858–1899)","writer and poet");
        put(10,"Vincas Mykolaitis-Putinas (1893–1967)","writer and poet");
        put(10,"Vincas Krėvė-Mickevičius (1882–1954)","writer and playwright");
        put(10,"Romualdas Granauskas (1939–)","writer about the identity crisis during the Soviet times");
        put(10,"Juozas Glinskis (1933–)","writer");
        put(10,"Balys Sruoga (1896–1947)","writer");
        put(10,"Antanas Vienuolis (real name Žukauskas 1882–1957)","writer");
        put(10,"Rolandas Kazlas (1969–)","well-known comedy actor");
        put(10,"Anthony Kiedis (1962-)","vocalist and member of Red Hot Chili Peppers group ;");
        put(10,"Regimantas Adomaitis (1937–)","theatre and film actor");
        put(10,"Adolfas Večerskis (1949–)","theatre and film actor");
        put(10,"Juozas Miltinis (1907–1994)","theater director from Panevėžys");
        put(10,"Eimuntas Nekrošius (1952–)","theater director");
        put(10,"Jonas Vaitkus (1944–)","theater director");
        put(10,"Jurga Ivanauskaitė (1961–2007)","the best known modern female writer");
        put(10,"Alanas Chošnau (1974–)","singer");
        put(10,"Marijonas Mikutavičius (1971–)","singer");
        put(10,"Petras Cvirka (1909–1947)","short story writer and active supporter of communism");
        put(10,"Andrius Mamontovas (1967–)","rock singer");
        put(10,"Czesław Miłosz (1911–2004)","recipient of the 1980 Nobel Prize for Literature");
        put(10,"Antanas Baranauskas (1835–1902)","priest and poet");
        put(10,"Antanas Strazdas (1760–1833)","priest and poet");
        put(10,"Linas Adomaitis (1976–)","pop singer");
        put(10,"Violeta Riaubiškytė (1974–)","pop singer");
        put(10,"Gintarė","pop artist");
        put(10,"Ilja Aksionovas (1996) (lt:Ilja Aksionovas)","pop and opera singer (boy soprano)");
        put(10,"Indrė Valantinaitė (born 1984)","poetess");
        put(10,"Kazys Binkis (1893–1942)","poet and playwright");
        put(10,"Jurgis Baltrušaitis (1873–1944)","poet and diplomat");
        put(10,"Henrikas Radauskas (1910–1970)","poet");
        put(10,"Tomas Venclova (1937–)","poet");
        put(10,"Mikalojus Konstantinas Čiurlionis (1875–1911)","painter and composer");
        put(10,"Mindaugas Rojus","opera singer (tenor / baritone)");
        put(10,"Violeta Urmanavičiūtė-Urmana","opera singer (soprano-mezzosoprano) appearing internationally");
        put(10,"Nomeda Kazlauskaitė-Kazlaus","opera singer (dramatic soprano) appearing internationally");
        put(10,"Stasys Povilaitis (1947–)","one of the popular singers during the Soviet period");
        put(10,"Virgilijus Noreika (1935–)","one of the most successful opera singers (tenor)");
        put(10,"Justinas Marcinkevičius (1930–2011)","one of the most prominent poets during the Soviet rule");
        put(10,"Arūnas Žebriūnas (1930–) (lt:Arūnas Žebriūnas)","one of the most prominent film directors during the Soviet rule");
        put(10,"Juozas Grušas (1901–1986)","one of the most productive writers and playwrights under the Soviet rule");
        put(10,"Vytautas Kernagis (1951–2008)","one of the most popular bards");
        put(10,"Mykolas Kleopas Oginskis (1765–1833)","one of the best composer of the late 18th century");
        put(10,"Sam Black (1970–)","musician and recording engineer");
        put(10,"Šarūnas Bartas (1964–)","modern film director");
        put(10,"Judita Vaičiūnaitė (1937–2001) (lt:Judita Vaičiūnaitė)","modern female poet exploring urban settings");
        put(10,"Algis Kizys (1960–)","long time bass player of post-punk");
        put(10,"Icchokas Meras (1934–)","Lithuanian-Jewish writer about the Holocaust");
        put(10,"Kristijonas Donelaitis (1714–1780)","Lithuanian Lutheran pastor and poet");
        put(10,"Leah Goldberg (1911–70)","Israeli poet");
        put(10,"Yemima Tchernovitz-Avidar (1909–98)","Israeli author");
        put(10,"Ingeborga Dapkūnaitė (1963–)","internationally successful actress");
        put(10,"Gintaras Januševičius (1985-)","internationally acclaimed pianist");
        put(10,"Jurgis Mačiūnas (1931–1978)","initiator of Fluxus movement");
        put(10,"Bernardas Brazdžionis (1907–2002)","influential romantic poet");
        put(10,"Oskaras Milašius (1877–1939)","French-Lithuanian writer and diplomat");
        put(10,"Jonas Mekas (1922–)","filmmaker");
        put(10,"Algimantas Puipa (1951–) (lt:Algimantas Puipa)","film director");
        put(10,"Balys Dvarionas (1904–1972)","composer");
        put(10,"Vincas Niekus (1886–1938) (lt:Vincas Niekus)","composer");
        put(10,"Česlovas Sasnauskas (1867–1916)","composer");
        put(10,"Jonas Švedas (1908–1971)","composer");
        put(10,"Oskaras Koršunovas (1969–)","best known modern theater director");
        put(10,"Martynas Mažvydas (1510–1563)","author of the first book in Lithuanian language");
        put(10,"Jurga Šeduikytė (1980–)","art rock musician");
        put(10,"Algirdas Kaušpėdas","architect and lead singer of Antis");
        put(10,"Osvaldas Balakauskas (1937–)","ambassador and classical composer");
        put(10,"Nijolė Narmontaitė (1959–) (lt:Nijolė Narmontaitė)","actress");
        put(10,"Donatas Banionis (1924–)","actor");
        put(10,"Arūnas Matelis (1961–)","acclaimed documentary director");
        put(10,"Salomėja Nėris (real name Salomėja Bačinskaitė-Bučienė","1904–1945)");
        put(10,"Šatrijos Ragana (real name Marija Pečkauskaitė","1877–1930)");
        put(10,"Juozas Tumas-Vaižgantas (real name Juozas Tumas","1869–1933)");
        put(10,"Vydūnas (real name Vilius Storostas","1868–1953)");
        put(10,"Maironis (real name Jonas Mačiulis","1862–1932)");
        put(10,"Žemaitė (real name Julija Beniuševičiūtė-Žymantienė","1845–1921)");
        put(11,"Ernst Glaser","violinist");
        put(11,"Gottfried von der Goltz","violinist");
        put(11,"Henning Kraggerud","violinist");
        put(11,"Arve Tellefsen","violin virtuoso");
        put(11,"Kirsten Flagstad","soprano");
        put(11,"Solveig Kringlebotn","soprano");
        put(11,"Paul Waaktaar-Savoy","songwriter and guitarist (a-ha)");
        put(11,"Christian Ingebrigtsen singer","song writer for A1");
        put(11,"Alexander Stenerud","singer-songwriter (Zuma)");
        put(11,"Marit Larsen","singer-songwriter");
        put(11,"Sondre Lerche","singer-songwriter");
        put(11,"Lene Marlin","singer-songwriter");
        put(11,"Maria Mena","singer-songwriter");
        put(11,"Ole Paus","singer-songwriter");
        put(11,"Marion Raven","singer-songwriter");
        put(11,"Hans Rotmo","singer-songwriter");
        put(11,"Kate Havnevik","singer-songwriter");
        put(11,"Sigurd Wongraven","singer-guitarist (Satyricon)");
        put(11,"Jarle Bernhoft","singer songwriter");
        put(11,"Hans Erik Husby aka Hank von Helvete","singer (Turbonegro)");
        put(11,"Roy Khan","singer (Kamelot)");
        put(11,"Kristian Espedal aka Gaahl","singer (Gorgoroth)");
        put(11,"Vibeke Stene","singer (ex-Tristania)");
        put(11,"Stian Thoresen","singer (Dimmu Borgir)");
        put(11,"Anni-Frid Lyngstad","singer (ABBA)");
        put(11,"Morten Harket","singer");
        put(11,"Tom Hugo","singer");
        put(11,"Sissel Kyrkjebø","singer");
        put(11,"Jørn Lande","singer");
        put(11,"Wenche Myhre","singer");
        put(11,"Kari Rueslåtten","singer");
        put(11,"Alexander Rybak","singer");
        put(11,"Njål Sparbo","singer");
        put(11,"Øystein Sunde","singer");
        put(11,"Jahn Teigen","singer");
        put(11,"Joachim Nielsen aka Jokke","rock singer");
        put(11,"Morten Aasdahl Eliassen AKA Opaque","Rapper.");
        put(11,"Tommy Flaaten AKA Tommy Tee Rapper","producer");
        put(11,"Lene Nystrøm","pop singer (Aqua)");
        put(11,"Geir Botnen","pianist");
        put(11,"Ørjan Hartveit","opera singer");
        put(11,"Björn Haugan","opera singer");
        put(11,"Ronni Le Tekrø","musician and guitarist");
        put(11,"Knut Schreiner","musician (Turbonegro");
        put(11,"Lars Nedland","musician (Solefald)");
        put(11,"Svein Berge","musician (Röyksopp)");
        put(11,"Morten Abel","musician (Mods");
        put(11,"Jørn Stubberud aka Necrobutcher","musician (Mayhem)");
        put(11,"Øystein Aarseth aka Euronymous","musician (Mayhem)");
        put(11,"Erlend Øye","musician (Kings of Convenience)");
        put(11,"Tomas Haugen aka Samoth","musician (Emperor)");
        put(11,"Vegard Sverre Tveitan aka Ihsahn","musician (Emperor)");
        put(11,"Øyvind Mustaparta","musician (Dimmu Borgir)");
        put(11,"Varg Vikernes","musician (Burzum) and convicted murderer");
        put(11,"Jan Garbarek","musician");
        put(11,"Erlend Øye","musician");
        put(11,"Arne Nordheim","modernist composer");
        put(11,"Magne Furuholmen","keyboardist and songwriter (a-ha)");
        put(11,"Tom Mathisen","humorist singer");
        put(11,"Sigmund Groven","harmonica virtuoso");
        put(11,"John Norum","guitarist (Europe)");
        put(11,"Toki Wartooth","guitarist (Dethklok)");
        put(11,"Terje Rypdal","guitarist");
        put(11,"Ian Haugland","drummer (Europe)");
        put(11,"Andy LaPlegua","DJ");
        put(11,"Carl Høgset","conductor (Grex Vocalis)");
        put(11,"Olav Kielland","conductor");
        put(11,"Herman Severin Løvenskiold","composer of La Sylphide ballet");
        put(11,"Edvard Grieg","composer");
        put(11,"Eivind Groven","composer");
        put(11,"Johan Halvorsen","composer");
        put(11,"Tone Groven Holmboe","composer");
        put(11,"David Monrad Johansen","composer");
        put(11,"Trond Kverno","composer");
        put(11,"Egil Monn-Iversen","composer");
        put(11,"Rikard Nordraak","composer");
        put(11,"Harald Sæverud","composer");
        put(11,"Johan Svendsen","composer");
        put(11,"Geirr Tveitt","composer");
        put(11,"Håvard Gimse","classical pianist");
        put(11,"Henny Mürer","choreographer and dancer");
        put(11,"Ivar F. Andresen","basso profundo opera singer");
        put(11,"Tord Øverland-Knudsen","bassist (The Wombats)");
        put(11,"Alf Prøysen","author and musician");
        put(12,"Peter Tomka (1956)","Vice");
        put(12,"Rudolf Schuster (1934)","the second president of modern Slovakia (He is of German and Hungarian ancestry)");
        put(12,"Michal Kováč (1930)","the first president of modern Slovakia");
        put(12,"Iveta Radičová (1956)","sixth prime minister of modern Slovakia");
        put(12,"Jozef Moravčík (1945)","second prime minister of modern Slovakia");
        put(12,"Mikuláš Dzurinda (1955)","fourth prime minister of modern Slovakia");
        put(12,"Vladimír Mečiar (1942)","first and third prime minister of modern Slovakia");
        put(12,"Robert Fico (1964)","fifth and seventh prime minister of modern Slovakia");
        put(12,"Maroš Šefčovič","EU Commissioner");
        put(12,"Ivan Gašparovič (1941)","3rd president of Slovakia previously chairman of the National Council of the Slovak Republic");
        put(12,"Jesse Ventura (1951)","38th Governor of the US state of Minnesota from 1999 to 2003 as well as an actor author and former professional wrestler; his parents were from Slovakia and his legal name is James George Janos");

        
        //Insert ContentValue Array using transactions
        database.insertPeople(peopleValues);
        
    }

    public void populateCountries() {

        putCountry(10, "Lithuania", "Lithuania.png");
        putCountry(9, "Latvia", "Latvia.png");
        putCountry(4, "Estonia", "Estonia.png");
        putCountry(5, "Finland", "Finland.png");
        putCountry(11, "Norway", "Norway.png");
        putCountry(1, "Austria", "Austria.png");
        putCountry(12, "Slovakia", "Slovakia.png");
        putCountry(7, "Hungary", "Hungary.png");
        putCountry(3, "Croatia", "Croatia.png");
        putCountry(8, "Italy", "Italy.png");
        putCountry(6, "France", "France.png");
        putCountry(2, "China", "China.png");

    }

    /**
     * insert Country record to database
     * @param id
     * @param title
     * @param flag
     */
    private void putCountry(int id, String title, String flag) {
        database.insertCountry(id, title, flag);
    }

    /**
     * put People to ContentValues ArrayList
     * @param country
     * @param name
     * @param about
     */
    private void put(int country, String name, String about) {

        ContentValues values = new ContentValues();
        values.put(MyDatabase.KEY_NAME, name);
        values.put(MyDatabase.KEY_DESCRIPTION, about);
        values.put(MyDatabase.KEY_COUNTRY_ID, country);
        peopleValues.add(values);
    }
}
